Add publish report job

diff --git a/.github/workflows/pw_e2e_chrome.yml b/.github/workflows/pw_e2e_chrome.yml
--- a/.github/workflows/pw_e2e_chrome.yml
+++ b/.github/workflows/pw_e2e_chrome.yml
@@ -101,14 +101,53 @@ jobs:
           path: playwright-report
           retention-days: 3
 
-      - name: Setup Pages
-        uses: actions/configure-pages@v2
-
-      - name: Upload artifacts
-        uses: actions/upload-pages-artifact@v2
+  publish_report:
+    name: Publish HTML Report
+    if: success() || needs.test.result == 'failure'
+    needs: [playwright-tests, merge-reports]
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    env:
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+    steps:
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v3
         with:
-          path: playwright-report
+          ref: gh-pages
 
-      - name: Deploy to Github Pages
-        id: deployment
-        uses: actions/deploy-pages@v1.2.9
+      - name: Set Git User
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Download zipped HTML report
+        uses: actions/download-artifact@v3
+        with:
+          name: playwright-report
+          path: ${{ env.HTML_REPORT_URL_PATH }}
+
+      - name: Push HTML Report
+        timeout-minutes: 3
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+  
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+  
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+
+      - name: Output Report URL as Worfklow Annotation
+        run: |
+          FULL_HTML_REPORT_URL=https://eugenepetrik.github.io/pw-github-pages-history/$HTML_REPORT_URL_PATH
+  
+          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
